### ISSUE TITLE
Possible error in loss weight assignment

### ISSUE THREAD

**Issue by Harshagarwal19** [amanshenoy/multilogue-net#21]
Hi Aman! 
Kudos on the amazing work! 

In the file `train_emotion.py`, I noticed you are using loss weights in your loss function. But the order for loss weights seems to be wrong.
```
if emotion=='anger': loss_weights = torch.FloatTensor([1/0.2128, 1/0.7872])
elif emotion=='happiness': loss_weights = torch.FloatTensor([1/0.5381, 1/0.4619])
elif emotion=='sadness': loss_weights = torch.FloatTensor([1/0.2546, 1/0.7454])
elif emotion=='disgust': loss_weights = torch.FloatTensor([1/0.1699, 1/0.8301])
elif emotion=='fear': loss_weights = torch.FloatTensor([1/0.0816, 1/0.9184])
elif emotion=='surprise': loss_weights = torch.FloatTensor([1/0.0986, 1/0.9014])
```
Consider emotion `fear` for instance, according to me the label 0 should be given less weight given it is the higher frequency label compared to label 1. But you code seems to do the opposite. 

Can you please have a look and clarify?

**Comment by amanshenoy** [comment]
Hi Harsh, 
looking into it you seem to be right. Flipping them should be the right way to go. Not really sure why this remained in the final upload.
