### ISSUE TITLE
pretrained model and or inference notebook?

### ISSUE THREAD

**Issue by noumanriazkhan** [amanshenoy/multilogue-net#3]
That's some awesome work you guys did and since I am working in the same area, would it be possible if you guys could release your pretrained models?

Thanks & Regards

**Comment by amanshenoy** [comment]
Hey @noumanriazkhan, thank you! 

The project was worked on between May and August 2019, and was pursued during the course of an internship. Most of the files that have not been uploaded have been lost. I will try to see if the systems still have those files and let you know soon!

If it helps, the number of epochs that have been reported to give the presented results are mildly overestimated and one can get quite decent results with a lower number of epochs.

**Comment by noumanriazkhan** [comment]
Thanks for your prompt response.

If you could explain a bit about dataset format and or preprocessing pipeline, that would be great.

Thanks

**Comment by amanshenoy** [comment]
Hey @noumanriazkhan , 

The dataset was mostly pre-processed from the CMU-Multimodal-SDK (https://github.com/A2Zadeh/CMU-MultimodalSDK). It should be incredibly easy getting the relevant information regarding the datasets used by us. 

After this, the dataset was arranged in a dictionary format as mentioned in our readme file's Implementation and Training section. The files processed in this manner are uploaded in data/ directory. 

This same dictionary format can also be used for training on another dataset or to be able to infer on another dataset!
