### ISSUE TITLE
name 'alpha' is not defined

### ISSUE THREAD

**Issue by ShantanuShinde** [amanshenoy/multilogue-net#6]
In the `train_categorical.py`, on line 55 in the `train_or_eval_model` function, variable named `alpha` is used but it is never defined. Same is the case with `train_emotion.py` line 55.

**Comment by atharva2101** [comment]
Yes. Facing the same problem here too.

**Comment by amanshenoy** [comment]
Alpha as a variable were the attention weights in general. Once both forward and backward attention weights were returned, alpha does not have any purpose, removing any lines including alpha should suffice.
