### ISSUE TITLE
Generating Feature Vectors

### ISSUE THREAD

**Issue by atharva2101** [amanshenoy/multilogue-net#7]
Hey, excellent job on the paper and the model.
I have trained the models, and I would like to test them on some videos of my own. If you could give any insights on how to generate the feature vectors from the videos, it would be great.

**Comment by amanshenoy** [comment]
Hey, thanks for going through our work!

Since everything regarding the dataset was processed using the CMU Multimodal SDK (https://github.com/A2Zadeh/CMU-MultimodalSDK), inference for the model is a particularly tedious task. When we had worked on the project we had attempted to individually extract features as given here (https://github.com/amanshenoy/multilogue-net/blob/master/data/README.md) and struggled particularly with FACET 2.0. 

If possible I would recommend you train the model using OpenFace for visual features. Extracting features from OpenFace is much easier. There might also be a provision in the SDK for custom datasets.

**Comment by atharva2101** [comment]
Hey, I'll certainly look into it.
In the paper, you've mentioned that you have averaged the sentiment label features for every utterance. Could you shed light on exactly what is being averaged here?

**Comment by amanshenoy** [comment]
The video and audio features are collected for units of time and text features are collected for words. So for any particular utterance, there are multiple features (multiple units of time for video and audio; multiple words in an utterance) for each modality. We followed a naive approach and averaged all the features for an utterance. So for any utterance, we have one video feat, one audio feat, and one text feat.

**Comment by atharva2101** [comment]
So let us say an utterance consists of 20 words; for 15 seconds. We average the GLoVe embeddings over the 20 words. Generally at what time segments, do we extract the audio and text features? And the vectors we obtain are then averaged over these timesteps, right?

**Comment by amanshenoy** [comment]
Yeah, the features are averaged. 

Text features will be at the word level, not the time segment level. Audio features on the other hand can be extracted for time segments of your choice, as long as there is at least one per utterance. 

Though averaging might not be the best strategy for this, it is what we had used for both training and testing.

**Comment by atharva2101** [comment]
Oh, thank you!
Could you tell me how you exactly created the pickle files from the csd files from the sdk for training the model over here? I would like to train it using OpenFace data.
Thanks in advanced.

**Comment by amanshenoy** [comment]
Hey, the instructions for how the pickles are to be made are in the readme here - (https://github.com/amanshenoy/multilogue-net/tree/master/data). For verification, you could compare to the pickles we generated here  - (https://github.com/amanshenoy/multilogue-net/tree/5d6b6ff8b1a26cf0762d6c1ca3a99917e881bf26/data) - by loading them and comparing the keys.

**Comment by atharva2101** [comment]
Thank you.
I tried comparing the features from the CMU Multimodal SDK after the alignment to the features from the pickle files on this repo. The features were different. Was there any normalisation of vectors or any other changes you did after alignment? Before creating the final pickle files?
